#!/usr/bin/env bash

_urlsave() {
	if [[ -e $mydir/data/urls.${config[server]}.db ]]; then source "$mydir/data/urls.${config[server]}.db"
	else declare -A urls=()
	fi

	local ticks nickname network chan i title rchan=${line[2]} change
	local text="${line[*]:3}"; text=( ${text/:/} )

	read -r ticks < <(date -u +%s)
	local change=0
	for i in "${text[@]}"; do
		[[ ${i,,} =~ ^[a-z]{3,}:// ]] || continue

		if ((${#urls[$i]})); then
			(( $(( $(date +%s) - ${urls[$i]} )) < ${urlsave[timeout]:-300} )) && continue
		fi

		read -r title < <(get_url_title "$i")
		if ((${#title})); then
			mapfile -t title < <(html2text -nobs <<<"$title") && title="${title[*]}"
		else
		 title=ENOTITLE
		fi

		urls[$i]=$ticks
		privmsg "$rchan" "^ ${title}" >&3
		change=1
	done
	((change)) && declare -p urls > "$mydir/data/urls.${config[server]}.db"
}
_urlsave
