#!/usr/bin/env bash
#set -o nounset

declare mydir="${0%/*}" running_daemons=()
[[ "${mydir}" = . ]] && mydir="$PWD"
[[ -d "$mydir/tmp" ]] || mkdir -p "${mydir}/tmp"
declare uname; read -r uname < <(uname)
declare version; read -r _ version _ < <(cd "$mydir" && git log -1 | head -n1)
version="${version:0:7}"
declare -A config
config[mydir]=$mydir
declare -A nicklist oplist holist volist
usage() {
	cat << EOF

	usage:

		${0##*/} -s <server> -p <port> [-n nick] [-P <server pass>] [-j '#chan'] [-z http://proxy:port] [-S int] [-Z timeout] [-v]

		-S		sleep \$S sec(s) before reconnecting
		-Z		proxy timeout
		-v		be verbose

EOF
	exit
}

_exit() {
	printf 'QUIT :leaving\n' >&3
	((${#running_daemons[@]})) && kill -9 "${running_daemons[@]}" &> /dev/null
}

_irc_login() {
	[[ ${config[ident]} ]] || config[ident]=${config[nick]}
	# send server password if any
	[[ ${config[password]:-nil} = nil ]] || printf 'PASS %s\n' "${config[password]}"
	## send user/nick infos
	printf 'NICK %s\nUSER %s %s localhost :%s\n' "$1" "${config[ident]}" "${config[server]}" "${config[nick]}"
}

_connect() {
	_log 'Connecting...' "${config[server]}"
	exec 3<> "/dev/tcp/${1}/${2}" || {
		_log 'ENOCONNECT' "${config[server]}" >&2
		return 1
	}
}

gen_nick() {
	local n nn i
	read -ra nn < <(printf '%s\n' "$1" | grep -Eo '.')
	while ((${#nn[@]})); do
		i=$(( RANDOM % ${#nn[@]}))
		n+="${nn[i]}"
		unset nn[i]
		nn=( ${nn[*]} )
	done
	printf '%s\n' "$n"
}

array_delete() {
	local items i array=()
	read -ra items <<<"$2"
	for i in "${items[@]}"; do
		[[ $1 = "$i" ]] || array+=("$i")
	done
	printf '%s\n' "${array[*]}"
}

update_lists_if_exists() {
	local nick=$1 newnick=$2 c
	for c in "${!nicklist[@]}"; do
		if in_array "$nick" "${nicklist[$c]}"; then
			nicklist[$c]="${nicklist[$chan]} $newnick"
		fi
	done

	for c in "${!oplist[@]}"; do
		if in_array "$nick" "${oplist[$c]}"; then
			oplist[$c]="${oplist[$chan]} $newnick"
		fi
	done

	for c in "${!holist[@]}"; do
		if in_array "$nick" "${holist[$c]}"; then
			holist[$c]="${holist[$chan]} $newnick"
		fi
	done

	for c in "${!volist[@]}"; do
		if in_array "$nick" "${volist[$c]}"; then
			volist[$c]="${volist[$chan]} $newnick"
		fi
	done
}

delete_from_lists() {
	local nick=$1 chan=$2 c
	for c in "${!nicklist[@]}"; do
		[[ $chan && $c = "$chan" ]] && continue
		nicklist[$c]="$(array_delete "$nick" "${nicklist[$c]}")"
	done

	for c in "${!oplist[@]}"; do
		[[ $chan && $c = "$chan" ]] && continue
		oplist[$c]="$(array_delete "$nick" "${oplist[$c]}")"
	done

	for c in "${!holist[@]}"; do
		[[ $chan && $c = "$chan" ]] && continue
		holist[$c]="$(array_delete "$nick" "${holist[$c]}")"
	done

	for c in "${!volist[@]}"; do
		[[ $chan && $c = "$chan" ]] && continue
		volist[$c]="$(array_delete "$nick" "${volist[$c]}")"
	done
}

# main function
tinyirc() {
	local var include skip REPLY mod line nick ident host var i chan array rnick="bbot${RANDOM}"
	[[ -d $mydir/tmp/${config[server]} ]] || mkdir -p "$mydir/tmp/${config[server]}"

	## load includes
	for i in "${mydir}"/includes/*.inc; do source "$i"; done
	## clean tmp files
	find "${mydir}/tmp/${config[server]}" -type f -delete

	# create bash tcp connection
	## through proxy
	if [[ ${config[http_proxy]} && ${config[irc_use_proxy]:-0} -gt 0 ]]; then
		local proxy="${config[http_proxy]/http:\/\/}"
		_connect "${proxy%:*}" "${proxy##*:}" || return
		## send proxy magics
		printf 'CONNECT %s:%s HTTP/1.0\n\n' "${config[server]}" "${config[port]}" >&3

	## direct connect
	else
		_connect "${config[server]}" "${config[port]}" || return
		_irc_login "${config[nick]}" >&3
	fi

	# set traps
	trap "rehash" SIGHUP
	trap "_exit" SIGINT

	# start background daemons
	for daemon in "${daemons[@]}"; do
		var=( "${mydir}"/daemons/*"${daemon}"*.daemon )
		[[ ${#var[@]} -eq 1 && -f $var ]] && source "$var"
		running_daemons+=($!)
	done

	# read until connection closes
	while IFS=$'\r' read -ru3 -t"${config[timeout]:-300}" REPLY; do
		((${config[irc_verbosity]:-0})) && _log "$REPLY" "${config[server]}"

		## if going over proxy
		if ((${#proxy})); then
			## return if proxy error
			[[ $REPLY =~ ^HTTP/1.[0-1]\ 200 ]] || return
			_irc_login "${config[nick]}" >&3
			unset -v proxy

		## ping/pong
		elif [[ $REPLY = PING* ]]; then
			_log "$REPLY <-> PONG" "${config[server]}"
			printf '%s\n' "${REPLY/I/O}" >&3
		## resend ping request ?
		elif [[ $REPLY = :+([a-zA-Z0-9_.-])\ PONG* && ${config[infiniping]:-0} -gt 0 ]]; then
			{
				sleep "${config[infiniping]:-5}"
				printf 'PING %s\n' "$RANDOM" >&3
			} &
		## parse other input
		elif [[ $REPLY = :* ]]; then

			# extract nick, ident and host
			IFS=!@ read -r nick ident host <<<"${line/:/}"

			# split line to array
			read -ra line <<<"$REPLY"

			## core IRC thing
			case "${line[1]}" in
				MODE)
					local chars="${line[3]}" item_count=3 char sign i
					for ((i=0;i<${#chars};i++)); do
						case "${chars:$i:1}" in
							\+|\-)
								sign="${chars:$i:1}"
							;;
							c|i|m|n|p|s|t|C|M|R)
								continue
							;;
							b|j|k|l|E|I|J)
								((item_count++));
								continue
							;;

							o) # (de)op
								((item_count++)); nick="${line[$item_count]}"
								read -ra foo <<<"${oplist[$chan]}"
								if [[ $sign = \+ ]]; then foo+=("$nick")
								else read -ra foo < <(array_delete "$nick" "${foo[*]}")
								fi
								oplist[$chan]="${foo[*]}"
							;;
							h) # (de)halfop
								((item_count++)); nick="${line[$item_count]}"
								read -ra foo <<<"${holist[$chan]}"
								if [[ $sign = \+ ]]; then foo+=("$nick")
								else read -ra foo < <(array_delete "$nick" "${foo[*]}")
								fi
								holist[$chan]="${foo[*]}"
							;;
							v) # (de)voice
								((item_count++)); nick="${line[$item_count]}"
								read -ra foo <<<"${volist[$chan]}"
								if [[ $sign = \+ ]]; then foo+=("$nick")
								else read -ra foo < <(array_delete "$nick" "${foo[*]}")
								fi
								volist[$chan]="${foo[*]}"
							;;
						esac
					done
				;;
				JOIN)
					chan=${line[2]/:/}
					if [[ $line = :"${mynick}"!* ]]; then
						nicklist[$chan]= oplist[$chan]= holist[$chan]= volist[$chan]=
					else
						nicklist[$chan]="${nicklist[$chan]} $nick"
						if [[ ${config[antiflood]:-nil = *:* ]] && is_flood "${ident}@${host}" "$chan" "${config[antiflood]}"; then
							 isop "$mynick" "$chan" && kick "$chan" "$ewnick" "kthxbai" >&3
						fi
					fi
				;;
				PART|KICK)
					chan=${line[2]}
					[[ $chan = :* ]] && chan=${chan/:/}
					delete_from_lists "$nick" "$chan"
				;;
				353)
					read -r _ _ _ _ chan _ <<<"$REPLY"
					nicks=(${REPLY##*:})
					read -ra array <<<"${nicklist[$chan]}"
					array=(${nicklist["$chan"]})
					for n in "${line[@]:5}"; do
						[[ $n = :* ]] && n=${n/$':'/}
						on=$n
						n=${n/$'@'/}; n=${n/$'%'/}; n=${n/$'+'/};
						n=${n/$'&'/}; n=${n/$'~'/}; n=${n/$'*'/};
						case $on in
							\@*) read -ra foo <<<"${oplist[$chan]}"
								   foo+=("$n")
								   oplist[$chan]=${foo[*]}
							;;
							\%*) read -ra foo <<<"${holist[$chan]}"
								   foo+=("$n")
								   holist[$chan]=${foo[*]}
							;;
							\+*) read -ra foo <<<"${volist[$chan]}"
								   foo+=("$n")
								   volist[$chan]=${foo[*]}
							;;
						esac
					done
					nicklist[$chan]="${array[*]}"
				;;
				433) ## nick is already used
					if [[ ${line[3]} = "${config[nick]}" ]]; then
						printf 'ISON %s\n' "${config[nick]}" >&3
					fi
					read -r nn < <(gen_nick "${config[nick]:-bbot}")
					printf 'NICK %s\n' "${nn}" >&3
				;;
				432) # nick too long
					if [[ ${server_config[NICKLEN]} ]]; then
						config[nick]="${config[nick]:0:${server_config[NICKLEN]}}"
						mynick=${config[nick]}
						printf 'NICK %s\n' "${config[nick]}" >&3
					else
						printf 'NICK bbot1%s\n' "$((RANDOM%100))" >&3
					fi
				;;
				303) ## ISON reply, keep checking ?
					if [[ ${line[3]} = : ]]; then
						printf 'NICK %s\n' "${config[nick]:-bbot}" >&3
					elif [[ $mynick != "${config[nick]}" ]]; then
						{ sleep 180; printf 'ISON %s\n' "${config[nick]}" >&3; } &
					fi
				;;
				461) ## nick is malformed
					[[ ${line[3]} = nick ]] && printf 'NICK bbot2%s\n' "$((RANDOM%100))" >&3
				;;
				001)
						{
						# usermodes
						printf 'MODE %s %s\n' "${line[2]}" "${config[umodes]:-+ixF}"
						# infiniping
						((${config[infiniping]:-0})) && printf 'PING %s\n' "$RANDOM"
						} >&3
				;;
				005)	# parse some server infos
					declare -gA server_config
					local item value
					read -ra array <<<"$REPLY"
					for i in "${array[@]:3}"; do
						if [[ $i = :* ]]; then
							break
						elif [[ $i = *=* ]]; then
							IFS=\= read -r item value <<<"$i"
							server_config[$item]=$value
						else
							server_config[$i]=1
						fi
					done
				;;
				376|422) ## end of MOTD, POTD or no MOTD
					declare -g mynick="${line[2]}"

					{ # send stuff to server
						# join chans
						((${#config[join]})) && printf 'JOIN %s\n' "${config[join]}"
						# regain nick?
						[[ $mynick = "${config[nick]}" ]] || printf 'ISON %s\n' "${config[nick]}"
					} >&3

				;;
				PRIVMSG|NOTICE)
					if [[ ${config[antiflood]:-nil = *:* ]] && is_flood "${ident}@${host}" "$chan" "${config[antiflood]}"; then
						 isop "$mynick" "$chan" && kick "$chan" "$ewnick" "kthxbai" >&3
					fi
					[[ ${line[*]:3} = *\#no@(log|op)* ]] && continue
				;;
				QUIT)	# regain nick
					delete_from_lists "$nick"
					if [[ ${line} = :"${config[nick]}"!* ]]; then
						printf 'NICK %s\n' "${config[nick]}" >&3
					fi
				;;

				NICK)
					newnick="${line[2]/:/}"
					if [[ ${nick/:/} = "$mynick" ]]; then
						mynick=$newnick
						_log "nick changed to '$newnick'" info

					elif [[ $line = :"${config[nick]}"!* ]]; then
						printf 'NICK %s\n' "${config[nick]}" >&3
					else
						if [[ ${config[antiflood]:-nil = *:* ]] && is_flood "${ident}@${host}" "$chan" "${config[antiflood]}"; then
							 isop "$mynick" "$chan" && kick "$chan" "$ewnick" "kthxbai" >&3
						fi
					fi

					update_lists_if_exists "$nick" "$newnick"
					delete_from_lists "$nick"
				;;
			esac

			## load user modules
			if ((${config[modules]:-0})); then
				{
				for mod in ${modules[${line[1]}]}; do
					[[ $mod && -f $mydir/modules/${mod}.module ]] && source "$mydir/modules/${mod}.module"
				done
				} &
			fi
		fi
	done
}

while getopts c:j:n:p:s:vx:z:P:S:BZ:O:I var; do
	case "$var" in
		c) declare config_file="$OPTARG";;
		Z) declare proxy_timeout="$OPTARG";;

		z) config[http_proxy]="$OPTARG";;
		j) config[join]="$OPTARG";;
		n) config[nick]="$OPTARG";;
		p) config[port]="$OPTARG";;
		s) config[server]="$OPTARG";;
		x) config[umodes]="$OPTARG";;
		I) config[infinite]=1;;
		v) config[irc_verbosity]=1;;
		j) config[join]="$OPTARG";;

		P) config[password]="$OPTARG";;
		S) config[sleep]="$OPTARG";;
		O) config[oper]="${OPTARG}";;
		*) usage;;
	esac
done

## source config file
[[ "${config_file:-nil}" = nil ]] || source "${config_file}"
mkdir -p "${config[mydir]}/data/${config[server]}"
touch "${config[mydir]}/data/${config[server]}/autoop"

## check if some vars are set
[[ "${config[server]:-nil}" = nil || "${config[port]:-nil}" = nil ]] && usage

## export proxy value, if any
if [[ -n ${config[http_proxy]} ]]; then
	export http_proxy="${config[http_proxy]}"
	export https_proxy="${config[http_proxy]}"
	export ftp_proxy="${config[http_proxy]}"
	export ftps_proxy="${config[http_proxy]}"
	export sftp_proxy="${config[http_proxy]}"
	export ssh_proxy="${config[http_proxy]}"

	export HTTP_PROXY="${config[http_proxy]}"
	export HTPPS_PROXY="${config[http_proxy]}"
	export FTP_PROXY="${config[http_proxy]}"
	export FTPS_PROXY="${config[http_proxy]}"
	export SFTP_PROXY="${config[http_proxy]}"
	export SSH_PROXY="${config[http_proxy]}"
fi

cobe_rebuild() {
  [[ -f $mydir/tmp/cobe.lock ]] && return
	touch "$mydir/tmp/cobe.lock"
	local changed=0 s k
	local files=( "$mydir"/cobe/tmp-*.*.* )
	if ((${#files[@]} >= 2)); then
		[[ -f $mydir/cobe/cobe.learn ]] && source "$mydir/cobe/cobe.learn"
		[[ -v cobe ]] || declare -gA cobe

		for s in "${files[@]}"; do
			[[ -f $s ]] || continue

			source "$s" && rm -v "$s"
			for k in "${!newcobe[@]}"; do
				if [[ ! ${cobe[$k]} ]]; then
					cobe["$k"]="${newcobe[$k]}"
					((changed++))
				fi
			done
		done
		((changed)) && declare -p cobe > "$mydir/cobe/cobe.learn"
		echo ">>> ${#cobe[@]} item(s) in memory (+${changed})" >&2
	fi
	rm -f "$mydir/tmp/cobe.lock"
}

while :; do
	((${hecketer[use_cobe]:-0})) && cobe_rebuild
	tinyirc
	[[ ${config[infinite]} ]] || exit 0
	sleep 5
done
